### ISSUE TITLE
Get the forum rss feed

### ISSUE THREAD

**Issue by cburschka** [sylae/ligrev#13]
might be cool if Ligrev linked to forum posts that got written. SMF does have an RSS feed that could be used for this.

(Unfortunately, iirc this Ligrev doesn't yet have a mechanism to asynchronously schedule tasks, which might require a PEAR library (Event?).)

I got bored and made some [untested prototype code](https://gist.github.com/cburschka/317a939a0fc0ea7bc6ac).

**Comment by sylae** [comment]
This is a pretty cool idea. I'll see about integrating it into ligrev.

Ligrev actually can tie into JAXL's event clock and use that, I don't know if the code is pushed but I've used it before.

**Comment by sylae** [comment]
Shitty example from LoungeSim: https://github.com/sylae/loungesim/blob/master/manager.php#L102

Also, given that I have access to the forum itself, it might also be possible to do something webhook-like to push a message to Ligrev to post (This is one of the long-term goals of the LCN project)

**Comment by cburschka** [comment]
Neat, I tweaked it to use that!

A direct hook would be great, though I haven't seen enough of SMF's documentation to know how that would work.

**Comment by sylae** [comment]
SMFs documentation is ass, and the codebase is ass. They have a primitive hook system but I dunno how/if it works. I've yet to see a package use it, so there's that.

Most likely a push-to-Ligrev solution would just have a couple lines of code injected into Post.php or something.
