### ISSUE TITLE
dice pools!

### ISSUE THREAD

**Issue by sudannasudanna** [sylae/ligrev#26]
(23:19:36) Nalyd: dice pools!
(23:20:22) Nalyd: some systems have you roll xdy and count the number of dice that go above a certain number as successes
(23:21:02) Nalyd: so, like, :roll 4d10 ob6 would show the number of dice that got a six or over
(23:21:24) Nalyd: and maybe also show number of ones
(23:32:23) Nalyd: or, maybe just a :pool xdy that shows every individual result cuz systems do different things sometimes. . .

**Comment by sylae** [comment]
This would actually be a good opportunity to fix the `xay` syntax, which did similar things now that I think on it.
