### ISSUE TITLE
Send user metadata for :tell commands.

### ISSUE THREAD

**Issue by cburschka** [sylae/ligrev#32]
:tell universally uses JID rather than room/nick, but it would still help to wrap it in a user span.

```html
<span data-jid="example@domain.com" class="jid-node-example jid-domain-domain.com">
   example@domain.com
</span>
```

This will add a user context menu (Invite / Direct message) and flairs.

**Comment by cburschka** [comment]
(Untested as yet)

**Comment by cburschka** [comment]
PS: Since the recipient will be in the room when the message is printed, they could be looked up in the roster and formatted with their current nick then. Same for the sender, if they're still there.

**Comment by sylae** [comment]
Aran - are you still sitting on this or am I okay to pull and tinker?

**Comment by cburschka** [comment]
Go ahead :)

-csb

**Comment by sylae** [comment]
> PS: Since the recipient will be in the room when the message is printed, they could be looked up in the roster and formatted with their current nick then. Same for the sender, if they're still there.

I like this idea, but for now I'm going to spin it off into another issue.
