### ISSUE TITLE
:faq uses accidental unescaped XML

### ISSUE THREAD

**Issue by sylae** [sylae/ligrev#35]
> Usage: `:faq set  `

should say

> Usage: `:faq set <keyword> <message>`

possible solution: htmlspecialchars. but this will mangle already-escaped things. I guess we could unspecialchars somehow, and then run htmlspecialchars, but that seems really hackey.

**Comment by cburschka** [comment]
I guess the best way is to decide whether or not the function expects
markup (already escaped) or text (not escaped), and then call it the same
way everywhere.

**Comment by sylae** [comment]
JAXL seems to handle this in a roundabout-helpful way. Since it ignores the HTML part, we only get the text part of the message. However, it seems to ignore any xml elements injected into the stream, as shown above. ie.
```xml
<body>I am a message with <script>bad intentions</script> and stuff.</body>
```
becomes simply `I am a message with  and stuff.` as far as Ligrev is concerned. While this can cause some issues with legitimate uses, like in the OP, right now it's on the XMPP client to make sure things are escaped properly, which Cadence, pidgin, etc all manage just fine.

So really, i'm assuming until shown otherwise that it's relatively-safe to use user messages. So its as simple as checking ourselves before we send this stuff.
