### ISSUE TITLE
Cadence resources break everything

### ISSUE THREAD

**Issue by sylae** [sylae/ligrev#43]
```php
$test = new \XMPPJid("sylae@calref.net/cadence/v1.10.0-calref-6-gf8ba682/1450810088764");
var_dump($test);

class XMPPJid#4 (4) {
  public $node =>
  string(5) "sylae"
  public $domain =>
  string(10) "calref.net"
  public $resource =>
  NULL
  public $bare =>
  string(16) "sylae@calref.net"
}
```
Caused by a bug in JAXL. 3.x JAXL trunk has it fixed. Upgrading has been a pain in the past, might as well try again.

**Comment by cburschka** [comment]
Is there a reason all the dots are removed?

**Comment by sylae** [comment]
The dots? The dots don't seem to be an issue (unless I'm missing something, are dots missing?), it's the multiple slashes that are messing it up. The submodule'd version of JAXL basically just does `explode("/", $tmp[1])` to get the resource, which, yeah.

**Comment by cburschka** [comment]
Oh, yeah, it needs to pass a limit to explode(), which I'm guessing the new
version does.

(I was confused by "calrefnet" and "v1100")

**Comment by sylae** [comment]
That...may be a github email thing? It renders fine on the web interface.

**Comment by cburschka** [comment]
Huh, the email really does strip dots from code. What a weird bug.

**Comment by sylae** [comment]
quick, report a bug to github's github! :P

**Comment by cburschka** [comment]
And done. ;)

**Comment by sylae** [comment]
this is resolved with the new jaxl version
