### ISSUE TITLE
Support XEP-0092 - Software Version

### ISSUE THREAD

**Issue by sylae** [sylae/ligrev#48]
http://www.xmpp.org/extensions/xep-0092.html

**Comment by cburschka** [comment]
Is this in production now? Because I don't get an answer from this:

    <iq from='Arancaytar@calref.net/cadence/v1.10.0-calref-112-gafd163e/1463834204419' 
        to='lounge@conference.calref.net/Ligrev' type='get' xmlns='jabber:client' id='4:sendIQ'>
        <query xmlns='jabber:iq:version'/>
    </iq>

**Comment by sylae** [comment]
Should. I'll look into it

**Comment by sylae** [comment]
This must've been an intermittent issue, or something funky was going on. Seems to be working properly now:

```xml
<iq from='sylae@calref.net/cadence/1.11.0-calref-10-g3e1e1c9/1487793523471'
  to='lounge@conference.calref.net/Ligrev' type='get' xmlns='jabber:client' id='9:sendIQ'>
  <query xmlns='jabber:iq:version'/>
</iq>
```
```xml
<iq xmlns='jabber:client' xml:lang='en'
  to='sylae@calref.net/cadence/1.11.0-calref-10-g3e1e1c9/1487793523471'
  from='lounge@conference.calref.net/Ligrev' type='result' id='9:sendIQ'>
  <query xmlns='jabber:iq:version'>
    <name>sylae/ligrev</name>
    <version>f9b6507d1f5f59762191562e73844225d5987e89</version>
    <os>Linux 3.16.0-4-amd64</os>
  </query>
</iq>
```
