### ISSUE TITLE
Ligrev RSS gets funky if there are multiple categories

### ISSUE THREAD

**Issue by sylae** [sylae/ligrev#76]
So RSS feeds can have multiple categories:
```xml
		<item>
		<title>To a poet.</title>
		<!-- ... -->
		<dc:creator><![CDATA[Nikki]]></dc:creator>
		<category><![CDATA[Poetry]]></category>
		<category><![CDATA[Writing]]></category>
		<category><![CDATA[darkness]]></category>
		<category><![CDATA[existence]]></category>
		<category><![CDATA[mental health]]></category>
		<category><![CDATA[poem]]></category>
		<category><![CDATA[poetry]]></category>
		<category><![CDATA[sadness]]></category>
		<category><![CDATA[words]]></category>
		<category><![CDATA[writing]]></category>
		<!-- ... -->
		</item>
```

Ligrev handles this weirdly

> (19:53:36) Ligrev: New post in Probably, Nikki.  / PoetryWritingdarknessexistencemental healthpoempoetrysadnesswordswriting: To a poet.

problem code appears to be https://github.com/sylae/ligrev/blob/master/classes/RSS.php#L75, just be as simple as a foreach loop or preferably an implode()? maybe qp has some magic for this

**Comment by cburschka** [comment]
Yeah, I didn't realize RSS categories were tags and non-hierarchical.

I suspect that we should either select the first (in this case "Poetry",
good as any) or just omit them if there is more than one. TODO: Find out if
RSS categories are ordered in any meaningful way or just occur in a random
order.

**Comment by cburschka** [comment]
Made a patch for :first
